# Generated by Django 3.2.18 on 2023-09-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='verticalrecoil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='cycletime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rateoffire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='reloadspeed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='spread',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='sway',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
