# Generated by Django 3.2.18 on 2023-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230906_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='type',
            field=models.CharField(blank=True, choices=[('compact', 'compact'), ('medium', 'medium'), ('long', 'long'), ('special', 'special'), ('shotgun', 'shotgun'), ('incendiary', 'incendiary'), ('poison', 'poison'), ('high velocity', 'high velocity'), ('spitzer', 'spitzer'), ('dumdum', 'dumdum'), ('FMJ', 'FMJ'), ('explosive', 'explosive'), ('flechette', 'flechette'), ('slug', 'slug'), ('dragonbreath', 'dragonbreath'), ('penny shot', 'penny shot'), ('starshell', 'starshell'), ('shredder', 'shredder'), ('poison bolt', 'poison bolt'), ('chaos bolt', 'chaos bolt'), ('choke bolt', 'choke bolt'), ('explosive bolt', 'explosive bolt'), ('shot bolt', 'shot bolt')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='ammo',
            name='weapon',
        ),
        migrations.AddField(
            model_name='ammo',
            name='weapon',
            field=models.ManyToManyField(related_name='ammo', to='api.Weapon'),
        ),
        migrations.RemoveField(
            model_name='damagerange',
            name='ammo',
        ),
        migrations.AddField(
            model_name='damagerange',
            name='ammo',
            field=models.ManyToManyField(related_name='damage_range', to='api.Ammo'),
        ),
    ]
